### ISSUE TITLE
"Atleast one video must be added to the sequence"

### ISSUE THREAD

**Issue by jessehorne** [Dirvann/video-conference-stitcher#2]
So I'm running into an issue that is pretty confusing for me at the moment. I have two users, each with a few separate audio/video streams because of them reconnecting throughout the call. When I set the startTime for their Media to be the actual millisecond start time/offset, I get the following error. I tried dividing the offset by 10, 100 and 1000 and in each case, the video generates (although the end result is not correct and all streams are basically put on the screen at once). It's just when the millisecond startTime offset is perhaps too large, it doesn't want to work?

```bash
(node:185499) UnhandledPromiseRejectionWarning: Error: At least one video must be added to the sequence
    at new SequenceStep (/home/jesse/Source/ameelio/video-processor/node_modules/video-conference-stitcher/lib/modules/SequenceStep.js:12:19)
    at /home/jesse/Source/ameelio/video-processor/node_modules/video-conference-stitcher/lib/modules/Sequence.js:89:34
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:185499) Error: At least one video must be added to the sequence
    at new SequenceStep (/home/jesse/Source/ameelio/video-processor/node_modules/video-conference-stitcher/lib/modules/SequenceStep.js:12:19)
    at /home/jesse/Source/ameelio/video-processor/node_modules/video-conference-stitcher/lib/modules/Sequence.js:89:34
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:185499) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

```

I've added some more output that is partly my own debugging output and the sort queue.

```bash
Adding User Media 327415 true false
Adding User Media 485155 true false
Adding User Media 703817 false true
Adding User Media 705332 true false
Adding Inmate Media 0 false true
Adding Inmate Media 105 true false
Adding Inmate Media 165553 false true
Adding Inmate Media 165687 true false
start encoding
Promise { <pending> }
> 
---- sort queue -----
 [
  { start_point: false, time: 2018635, media_id: 3 },
  { start_point: false, time: 2018509, media_id: 7 },
  { start_point: false, time: 2018413, media_id: 2 },
  { start_point: false, time: 857237, media_id: 6 },
  { start_point: true, time: 705332, media_id: 7 },
  { start_point: true, time: 703817, media_id: 6 },
  { start_point: false, time: 543418, media_id: 5 },
  { start_point: true, time: 485155, media_id: 5 },
  { start_point: false, time: 387201, media_id: 4 },
  { start_point: true, time: 327415, media_id: 4 },
  { start_point: true, time: 165687, media_id: 3 },
  { start_point: true, time: 165553, media_id: 2 },
  { start_point: false, time: 133557, media_id: 1 },
  { start_point: false, time: 133160, media_id: 0 },
  { start_point: true, time: 105, media_id: 1 },
  { start_point: true, time: 0, media_id: 0 }

```

**Comment by information-security** [comment]
I am experiencing the same issue. Any reason this issue is closed?
